# https://scrutinizer-ci.com/docs/configuration/build_reference

# https://scrutinizer-ci.com/docs/configuration/build_reference

build:
    nodes:
        php56:
            environment:
                php: 5.6
            requires:
                # will only run when build is related to the "1.3" branch
                - branch: 1.3
            tests:
                override:
                    - php-scrutinizer-run

filter:
    excluded_paths:
        - "docs/"
        - "tests/"

checks:
    php:
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true
