language: php

php:
  - 5.6
  - nightly

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-source

script:
 - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
